#include "activation.h"

#include <algorithm>
#include <shared_mutex>
#include <taskflow/taskflow.hpp>

#include "bitio.h"
#include "layout.h"
#include "notePoolManager.h"
#include "profile.h"

namespace {

// Note IDs generated by the pool are always NOTE_ID_LENGTH characters, so a
// record is [2 x int][5 x double][noteID + 1][subNoteID + 1].
constexpr size_t NOTE_RECORD_FIXED_SIZE =
    sizeof(int) * 2 + sizeof(double) * 5;
constexpr size_t NOTE_RECORD_MAX_SIZE =
    NOTE_RECORD_FIXED_SIZE + 2 * (NOTE_ID_LENGTH + 1);
constexpr size_t PARALLEL_PROPS_BATCH_THRESHOLD = 256;

size_t note_record_size(const Note &note) {
    return NOTE_RECORD_FIXED_SIZE + note.noteID.size() + 1 +
           note.subNoteID.size() + 1;
}

}  // namespace

void NoteActivationManager::set_range(double curTime, double curSpeed) {
    currentTime = curTime;
    noteSpeed = curSpeed;

    timeRange = {
        currentTime,
        currentTime + (ACTIVATION_AHEAD_PIXELS +
                       std::max(BASE_RES_H - JUDGE_LINE_BELOW_FROM_BOTTOM,
                                BASE_RES_W / 2 - JUDGE_LINE_SIDE_FROM_EDGE)) /
                          noteSpeed};
    timeRangeMin = {
        currentTime,
        currentTime + std::min(BASE_RES_H - JUDGE_LINE_BELOW_FROM_BOTTOM,
                               BASE_RES_W / 2 - JUDGE_LINE_SIDE_FROM_EDGE) /
                          noteSpeed};
}

void NoteActivationManager::recalculate() {
    PROFILE_SCOPE("Note Activation Manager Recalculate");

    activeNotes.clear();
    activeHolds.clear();
    lastingHolds.clear();

    auto& poolMan = get_note_pool_manager();
    poolMan.array_sort_request();
    auto& noteArray = poolMan.noteArray;

    // Check normal notes
    int lb = poolMan.get_index_lowerbound(timeRange.first);
    int hb = poolMan.get_index_upperbound(timeRange.second);
    for (int i = lb; i < hb; i++) {
        // Use strict condition for LR side notes.
        if (noteArray[i]->side > 0 &&
            noteArray[i]->time >
                timeRange.first +
                    (BASE_RES_W / 2.0 - JUDGE_LINE_SIDE_FROM_EDGE) / noteSpeed)
            continue;
        if (noteArray[i]->get_note_type() <= NOTE_TYPE::HOLD) {
            activeNotes.push_back({noteArray[i]->time, noteArray[i]->noteID});
            if (noteArray[i]->get_note_type() == NOTE_TYPE::HOLD) {
                activeHolds.push_back(
                    {noteArray[i]->time, noteArray[i]->noteID});
            }
        } else {
            activeNotes.push_back(
                {noteArray[i]->beginTime, noteArray[i]->subNoteID});
            activeHolds.push_back(
                {noteArray[i]->beginTime, noteArray[i]->subNoteID});
            if (noteArray[i]->beginTime < currentTime) {
                lastingHolds.push_back(
                    {noteArray[i]->beginTime, noteArray[i]->subNoteID});
            }
        }
    }

    // Check long holds.
    for (const auto& note_ptr : poolMan.holdArray) {
        const auto& note = *note_ptr;
        if (note.lastTime < timeRangeMin.second - timeRangeMin.first)
            break;
        if (note.time <= timeRangeMin.first &&
            note.time + note.lastTime > timeRangeMin.second) {
            activeNotes.push_back({note.time, note.noteID});
            lastingHolds.push_back({note.time, note.noteID});
            activeHolds.push_back({note.time, note.noteID});
        }
    }

    // Remove duplicates
    static auto unique_and_sort = [](auto& vec) {
        std::sort(vec.begin(), vec.end());
        vec.erase(std::unique(vec.begin(), vec.end()), vec.end());
    };

    unique_and_sort(activeNotes);
    unique_and_sort(activeHolds);
    unique_and_sort(lastingHolds);
}

void NoteActivationManager::clear() {
    activeNotes.clear();
    activeNotes.shrink_to_fit();
    activeHolds.clear();
    activeHolds.shrink_to_fit();
    lastingHolds.clear();
    lastingHolds.shrink_to_fit();
}

void NoteActivationManager::bitwrite_active_notes(char* buffer) const {
    char* ptr = buffer;
    bitwrite<int>(ptr, activeNotes.size());
    for (const auto& note : activeNotes) {
        bitwrite<string>(ptr, note.second);
    }
}

void NoteActivationManager::bitwrite_lasting_holds(char* buffer) const {
    char* ptr = buffer;
    bitwrite<int>(ptr, lastingHolds.size());
    for (const auto& note : lastingHolds) {
        bitwrite<string>(ptr, note.second);
    }
}

size_t NoteActivationManager::get_active_notes_props_bound() const {
    // Worst case: every active note is a hold with a sub-note.
    return sizeof(int) + activeNotes.size() * 2 * NOTE_RECORD_MAX_SIZE;
}

bool NoteActivationManager::bitwrite_active_notes_props(char* buffer) const {
    struct Record {
        const Note* note;
        size_t offset;
        size_t size;
    };
    std::vector<Record> records;
    records.reserve(activeNotes.size() * 2);

    // Resolve every active note (plus each hold's sub-note) in one locked
    // pass. The pool is quiescent while the GM thread is inside this call,
    // so the resolved pointers stay valid for the write phase below.
    {
        auto& poolMan = get_note_pool_manager();
        std::shared_lock lock(poolMan.mtxNoteOps);
        for (const auto& [time, id] : activeNotes) {
            const auto it = poolMan.noteInfoMap.find(id);
            if (it == poolMan.noteInfoMap.end()) {
                continue;
            }
            const Note* note = it->second.pointer.get();
            records.push_back({note, 0, note_record_size(*note)});
            if (note->get_note_type() == NOTE_TYPE::HOLD &&
                !note->subNoteID.empty()) {
                const auto subIt = poolMan.noteInfoMap.find(note->subNoteID);
                if (subIt != poolMan.noteInfoMap.end()) {
                    const Note* sub = subIt->second.pointer.get();
                    records.push_back({sub, 0, note_record_size(*sub)});
                }
            }
        }
    }

    size_t total = 0;
    for (auto& record : records) {
        record.offset = total;
        total += record.size;
    }
    char* const body = buffer + sizeof(int);

    if (records.size() >= PARALLEL_PROPS_BATCH_THRESHOLD) {
        // Write each record into its disjoint byte range concurrently.
        auto& executor = get_shared_taskflow_executor();
        const size_t chunkCount =
            std::max<size_t>(1, executor.num_workers() * 4);
        const size_t perChunk = (records.size() + chunkCount - 1) / chunkCount;
        tf::Taskflow taskflow;
        for (size_t chunk = 0; chunk < chunkCount; chunk++) {
            const size_t begin = chunk * perChunk;
            const size_t end = std::min(records.size(), begin + perChunk);
            if (begin >= end) {
                break;
            }
            taskflow.emplace([body, &records, begin, end]() {
                for (size_t i = begin; i < end; i++) {
                    records[i].note->write(body + records[i].offset);
                }
            });
        }
        executor.run(taskflow).get();
    } else {
        for (const auto& record : records) {
            record.note->write(body + record.offset);
        }
    }

    char* ptr = buffer;
    bitwrite<int>(ptr, static_cast<int>(records.size()));
    return true;
}

NoteActivationManager& get_note_activation_manager() {
    static NoteActivationManager instance;
    return instance;
}
