/// @description Render a triangulated background using DyCore's native delaunay buffer API.
/// @param {Any}    tri_struct Struct generated by trianglify_generate(), contains width/height/points.
/// @param {Array}  colors     [0]=bottom-right color, [1]=top-left color, [2]=mouse light color.
/// @param {Real}   threshold  Normalized vertical fade threshold [0,1), higher = more area kept transparent.
function trianglify_draw(tri_struct, colors, threshold = 0) {
	var w = tri_struct.width;
	var h = tri_struct.height;
	
	// Keep native buffers alive across frames so we do not continuously
	// allocate/free during animation, which would fragment memory and
	// add overhead every step when the point count is stable.
	static __tri_buf_in = -1;
	static __tri_buf_in_pts = -1;
	static __tri_buf_out = -1;
	static __tri_buf_out_cap = 0;
	
	// Pack current point cloud into the input buffer as f64 pairs.
	// The native side expects: [u32 pointCount][x0][y0][x1][y1]...
	var _pts = tri_struct.points;
	var _pcount = array_length(_pts);
	
	// Recreate the input buffer only when the point count changes or
	// the buffer was destroyed, so we keep the cost proportional to
	// structural changes rather than per-frame drawing.
	if ((__tri_buf_in == -1) || !buffer_exists(__tri_buf_in) || (__tri_buf_in_pts != _pcount)) {
		if ((__tri_buf_in != -1) && buffer_exists(__tri_buf_in)) buffer_delete(__tri_buf_in);
		// 4 bytes header (u32 count) + 2 coordinates per point * 8 bytes (f64).
		__tri_buf_in = buffer_create(4 + _pcount * 2 * 8, buffer_grow, 1);
		__tri_buf_in_pts = _pcount;
	}
	
	buffer_seek(__tri_buf_in, buffer_seek_start, 0);
	buffer_write(__tri_buf_in, buffer_u32, _pcount);
	for (var i = 0; i < _pcount; i++) {
		buffer_write(__tri_buf_in, buffer_f64, _pts[i].x);
		buffer_write(__tri_buf_in, buffer_f64, _pts[i].y);
	}
	
	// Ensure output buffer capacity for the worst‑case triangle count.
	// Delaunay triangulation in 2D is O(n) triangles, so 2*n is a safe
	// linear upper bound here, then each triangle has 3 vertices * 2
	// coordinates * 8 bytes f64, plus a u32 triangleCount header.
	var _tri_upper = max(2 * _pcount, 8);
	var _need_guess = 4 + _tri_upper * 6 * 8;
	if ((__tri_buf_out == -1) || !buffer_exists(__tri_buf_out)) {
		__tri_buf_out_cap = _need_guess;
		__tri_buf_out = buffer_create(__tri_buf_out_cap, buffer_grow, 1);
	} else if (__tri_buf_out_cap < _need_guess) {
		// Grow the buffer only when the previous capacity is insufficient
		// to avoid reallocations on every native call.
		buffer_delete(__tri_buf_out);
		__tri_buf_out_cap = _need_guess;
		__tri_buf_out = buffer_create(__tri_buf_out_cap, buffer_grow, 1);
	}
	
	// Call native triangulation (coordFormat=1 means f64 layout).
	// Negative return values mean "required size" so we can retry once
	// with an exact capacity instead of guessing repeatedly.
	var _ret = DyCore_delaunator_buffer(buffer_get_address(__tri_buf_in), buffer_get_address(__tri_buf_out), __tri_buf_out_cap, 1.0);
	if (_ret < 0) {
		var _need = -_ret;
		buffer_delete(__tri_buf_out);
		__tri_buf_out_cap = _need;
		__tri_buf_out = buffer_create(__tri_buf_out_cap, buffer_grow, 1);
		_ret = DyCore_delaunator_buffer(buffer_get_address(__tri_buf_in), buffer_get_address(__tri_buf_out), __tri_buf_out_cap, 1.0);
		if (_ret < 0) {
			// If triangulation keeps failing, skip this frame to avoid
			// stalling the render loop; we keep existing contents instead.
			return;
		}
	}
	
	var _tri_count = _ret;
	
	// Draw triangles directly to the current target using a replace blend
	// (ONE,ZERO). This lets the caller treat the target surface as a pure
	// background layer that is fully controlled by this function.
	gpu_push_state();
	gpu_set_blendmode_ext(bm_one, bm_zero);
	draw_clear_alpha(c_black, 0);
	draw_set_alpha(1);
	draw_set_color(c_white);
	
	buffer_seek(__tri_buf_out, buffer_seek_start, 0);
	var _read_tri_count = buffer_read(__tri_buf_out, buffer_u32);
	
	// Triangles are encoded as a flat list of vertices:
	// [x1][y1][x2][y2][x3][y3] * triangleCount.
	draw_primitive_begin(pr_trianglelist);
	for (var t = 0; t < _read_tri_count; t++) {
		var x1 = buffer_read(__tri_buf_out, buffer_f64);
		var y1 = buffer_read(__tri_buf_out, buffer_f64);
		var x2 = buffer_read(__tri_buf_out, buffer_f64);
		var y2 = buffer_read(__tri_buf_out, buffer_f64);
		var x3 = buffer_read(__tri_buf_out, buffer_f64);
		var y3 = buffer_read(__tri_buf_out, buffer_f64);
		
		var cx = (x1 + x2 + x3) / 3;
		var cy = (y1 + y2 + y3) / 3;
		
		// Base color is a 2‑corner gradient; then we merge in a soft
		// mouse‑centric "spot light" so the background reacts to input.
		var _color = __2corner_color_merge(colors, cx, cy, w, h);
		_color = __trisys_mouselight(_color, cx, cy, colors[2]);
		draw_set_color(_color);
		
		// Vertical fade: triangles near the top fade out first.
		// threshold defines which normalized Y starts to appear;
		// below this value the alpha stays at 0.
		var _alp = cy / h;
		_alp = max(_alp - threshold, 0);
		_alp = lerp(0, 1, _alp / (1 - threshold));
		
		draw_vertex_color(x1, y1, _color, 1);
		draw_vertex_color(x2, y2, _color, 1);
		draw_vertex_color(x3, y3, _color, 1);
	}
	draw_primitive_end();
	gpu_pop_state();
}

function trianglify_generate(w, h, speedRange, cellSize=75, variance=0.75) {
	var _trianglify = {
		width: w,
		height: h,
		points: []
	};
	var colCount = floor(w / cellSize) + 4;
    var rowCount = floor(h / cellSize) + 4;
    var bleedX = ((colCount * cellSize) - w) / 2;
    var bleedY = ((rowCount * cellSize) - h) / 2;
    var cellJitter = cellSize * variance;
    var getJitter = function (c) { return (dyc_random(1) - 0.5) * c; } ;
    var halfCell = cellSize / 2;
    for(var i=0; i<colCount; i++)
    for(var j=0; j<rowCount; j++) {
    	var _corner = !(((i==0)+(i==colCount-1)+(j==0)+(j==rowCount-1)) >= 2);
    	array_push(_trianglify.points, {
    		x : -bleedX + i * cellSize + halfCell + _corner * getJitter(cellJitter),
    		y : -bleedY + j * cellSize + halfCell + _corner * getJitter(cellJitter),
    		vx : (in_between(i, 2, colCount - 3) && in_between(j, 2, rowCount - 3))
    			* dyc_random_range(speedRange[0], speedRange[1]) * (dyc_irandom(1)*2-1)
    			* global.timeManager.get_fps_scale(),
    		vy : (in_between(i, 2, colCount - 3) && in_between(j, 2, rowCount - 3))
    			* dyc_random_range(speedRange[0], speedRange[1]) * (dyc_irandom(1)*2-1)
    			* global.timeManager.get_fps_scale()
    	});
    }
    
    return _trianglify;
}

function trianglify_step(tri_struct) {
	var _arr = tri_struct.points;
	var _count = array_length(_arr);
	if(_count == 0) return;
	var dt = global.timeManager.get_delta() / 1000000;
	static _stepBuf = buffer_create(4 + 375 * 32, buffer_grow, 1);
	buffer_seek(_stepBuf, buffer_seek_start, 0);
	buffer_write(_stepBuf, buffer_u32, _count);
	for(var i = 0; i < _count; i++) {
		buffer_write(_stepBuf, buffer_f64, _arr[i].x);
		buffer_write(_stepBuf, buffer_f64, _arr[i].y);
		buffer_write(_stepBuf, buffer_f64, _arr[i].vx);
		buffer_write(_stepBuf, buffer_f64, _arr[i].vy);
	}
	dyc_trianglify_step(_stepBuf, dt, tri_struct.width, tri_struct.height);
	buffer_seek(_stepBuf, buffer_seek_start, 4);
	for(var i = 0; i < _count; i++) {
		_arr[i].x = buffer_read(_stepBuf, buffer_f64);
		_arr[i].y = buffer_read(_stepBuf, buffer_f64);
		_arr[i].vx = buffer_read(_stepBuf, buffer_f64);
		_arr[i].vy = buffer_read(_stepBuf, buffer_f64);
	}
}

function __trisys_sparkle(pos, w, h, jitterFactor = 0.15) {
	return [
		pos[0]+(dyc_random(1)-0.5)*jitterFactor*w,
		pos[1]+(dyc_random(1)-0.5)*jitterFactor*h,
		];
}

function __trisys_mouselight(col, x, y, lcol = c_white, radius = 300, alp = 0.4) {
	return merge_color(col, lcol, lerp(0, alp, max(1-point_distance(x, y, mouse_x, mouse_y)/radius, 0)));
}

function __trisys_centroid(str) {
	return [(str.p1[0]+str.p2[0]+str.p3[0])/3, (str.p1[1]+str.p2[1]+str.p3[1])/3];
}

function __2corner_color_merge(colors, x, y, w, h) {
	x = clamp(x, 0, w);
	y = clamp(y, 0, h);
	var _std = sqrt(w*w+h*h);
	var _col = c_black;
	_col = merge_color(_col, colors[0], point_distance(0, 0, x, y)/_std);
	_col = merge_color(_col, colors[1], point_distance(w, h, x, y)/_std);
	return _col;
}